### ISSUE TITLE
ReferenceError: invalid assignment left-hand side

### ISSUE THREAD

**Issue by Buttars** [MarkTiedemann/device-discovery#1]
ReferenceError: invalid assignment left-hand side

`module.exports = ({ type = 'ICMP', iface = 'WiFi', start = 2, end = 254, port = 1, timeout = 3000, retries = 0, excludeSelf = true } = {}) => {`

Seems like the => after the parameters is throwing an error.

Is this repo still managed?

**Comment by Buttars** [comment]
I'm not able to test it but maybe the following will fix it?

```
module.exports = ({ type = 'ICMP', iface = 'WiFi', start = 2, end = 254, port = 1, timeout = 3000, retries = 0, excludeSelf = true } = {}) => {
    const address = getIfaceAddress(iface);
    const range = getIfaceRange(address);

    return getScanner(type)({range, start, end, port, timeout, retries, exclude: excludeSelf ? address : false});
}
```

**Comment by MarkTiedemann** [comment]
Yes, this module is still maintained.

The `ReferenceError` occured because Node versions <6 do not support [default parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters).

Thus, in order to use this module, please upgrade to at least Node 6.

I'd recommend using a Node Version Manager to easily upgrade and switch between different Node versions. See: [`nvm`](https://github.com/creationix/nvm) or [`nvm-windows`](https://github.com/coreybutler/nvm-windows).

PS: Check the `package.json`'s engine property to see which Node versions are supported:

```json
{
  "engines": {
    "node": ">=6.0.0"
  }
}
```
